FROM hello-world
LABEL maintainer "Max Biliaievskyi <mbiliaie@student.unit.ua>"

# Just an image for testing. A clone of Docker's hello-world official container

# docker build -t hw .
# docker run hw